### ISSUE TITLE
No excluded languages

### ISSUE THREAD

**Issue by igouy** [bluenote10/SimpleLanguageBenchmarks#1]
> Last updated: 2017-03-05 

> In contrast to the [benchmarksgame](http://benchmarksgame.alioth.debian.org/play.html) no languages are forbidden per-se. In particular the goal is to add languages which are excluded in other benchmarks (e.g. Nim, Crystal, and Julia).

Given that neither Crystal nor Julia are shown in the result overview.

Given that 9 language implementations are shown, in contrast to the 37 language implementations shown on benchmarks game.

Is "no languages are forbidden per-se" not true? Not worth anything? Not scalable?

**Comment by bluenote10** [comment]
This was written ~8 years ago. At that time the author of the benchmarks game has explicitly forbidden certain languages I was interested in. Most likely a lot has changed in the meantime.

**Comment by igouy** [comment]
I am the person who you say has explicitly forbidden blah blah.

["The guy that runs it arbitrarily decided to stop tracking some languages he didn't care about…"](https://benchmarksgame-team.pages.debian.net/benchmarksgame/sometimes-people-just-make-up-stuff.html#maintenance-burden)

Are they "forbidden per se"  or is it just like what you've done ?

**Comment by bluenote10** [comment]
I don't really understand the question. Isn't this more a question about the benchmarksgame?

In any case the difference I wanted to point out: The benchmarksgame clearly rejects certain languages. This repo does not reject languages per se. The list of shown languages is just what I had time and interest to implement back then. Feel free to open a PR adding a language of your choice if you want to add any.

**Comment by igouy** [comment]
Just like you —

The benchmarksgame does not reject languages per se.

The list of shown languages is just what I had time and interest to implement back then. 

I know it will take more time than I choose. Been there; done that.

**Comment by bluenote10** [comment]
> The benchmarksgame does not reject languages per se.

It certainly did back then. At that time, we were trying to get an entry for Nim. If I remember correctly we had all the implementations ready, but they were rejected to be added.

In contrast, this repo has rejected 0 entries -- admittedly, the repo has received 0 requests so far :wink: but in any case I'm happy to add anything that comes with a complete set of implementation (and that is certainly not the case for the benchmarksgame).

**Comment by igouy** [comment]
> but they were rejected to be added

Just like you — "what I had time and interest to implement".

Not "forbidden per-se".

Otherwise you've made one rule for yourself and a very different rule for others.

**Comment by bluenote10** [comment]
> Just like you — "what I had time and interest to implement".

No, we had implemented the benchmarks, and they got rejected. The time had already been invested by us, and yet it was rejected. I've never done that, why are you accusing me of that?! You can simply check the history of pull request to verify that I have never rejected any contribution.

What are you even trying to accomplish with opening this issue? Do you want me to rephrase the readme or add another language or what?

**Comment by igouy** [comment]
Wondering how you justify one rule for yourself and a different rule for others.

> The time had already been invested by us, and yet it was rejected.

So you didn't ask if I wanted to invest my time nor did you ask if I was interested.

Not "forbidden per-se".

**Comment by bluenote10** [comment]
> So you didn't ask if I wanted to invest my time nor did you ask if I was interested.

That's precisely the point: There is no need to ask for this repo. Everything is welcome! That's why the rule here is different than the benchmarkgame.

Let's use our time for something more productive than this discussion.
